In [10]:
# Import required libraries for data analysis
# Load HR attrition dataset into a DataFrame
# Preview first 5 rows to understand structure

import pandas as pd

df = pd.read_csv("IBM.csv")
df.head()

,Age,Attrition,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,WorkLifeBalance,YearsAtCompany
0,41,Yes,Sales,1,2,Life Sciences,2,4,Single,5993,8,1,6
1,49,No,Research & Development,8,1,Life Sciences,3,2,Married,5130,1,3,10
2,37,Yes,Research & Development,2,2,Other,4,3,Single,2090,6,3,0
3,33,No,Research & Development,3,4,Life Sciences,4,3,Married,2909,1,3,8
4,27,No,Research & Development,2,1,Medical,1,2,Married,3468,9,3,2

In [9]:
# Review dataset structure, column names, row counts, and data types

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      1470 non-null   int64
 1   attrition                1470 non-null   object
 2   department               1470 non-null   object
 3   distancefromhome         1470 non-null   int64
 4   education                1470 non-null   int64
 5   educationfield           1470 non-null   object
 6   environmentsatisfaction  1470 non-null   int64
 7   jobsatisfaction          1470 non-null   int64
 8   maritalstatus            1470 non-null   object
 9   monthlyincome            1470 non-null   int64
 10  numcompaniesworked       1470 non-null   int64
 11  worklifebalance          1470 non-null   int64
 12  yearsatcompany           1470 non-null   int64
dtypes: int64(9), object(4)
memory usage: 149.4+ KB

In [8]:
# Check for missing values in each column

df.isnull().sum()

age                        0
attrition                  0
department                 0
distancefromhome           0
education                  0
educationfield             0
environmentsatisfaction    0
jobsatisfaction            0
maritalstatus              0
monthlyincome              0
numcompaniesworked         0
worklifebalance            0
yearsatcompany             0
dtype: int64

In [17]:
# Replace spaces with underscores for easier coding and SQL queries
# Convert column names to lowercase for consistency

df.columns= df.columns.str.strip().str.lower().str.replace(" ", "_")

In [18]:
# Check for missing values in each column

df.duplicated().sum()

0

In [19]:
# Generate summary statistics for numerical columns

df.describe()

,age,distancefromhome,education,environmentsatisfaction,jobsatisfaction,monthlyincome,numcompaniesworked,worklifebalance,yearsatcompany
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,9.192517,2.912925,2.721769,2.728571,6502.931293,2.693197,2.761224,7.008163
std,9.135373,8.106864,1.024165,1.093082,1.102846,4707.956783,2.498009,0.706476,6.126525
min,18.000000,1.000000,1.000000,1.000000,1.000000,1009.000000,0.000000,1.000000,0.000000
25%,30.000000,2.000000,2.000000,2.000000,2.000000,2911.000000,1.000000,2.000000,3.000000
50%,36.000000,7.000000,3.000000,3.000000,3.000000,4919.000000,2.000000,3.000000,5.000000
75%,43.000000,14.000000,4.000000,4.000000,4.000000,8379.000000,4.000000,3.000000,9.000000
max,60.000000,29.000000,5.000000,4.000000,4.000000,19999.000000,9.000000,4.000000,40.000000

In [20]:
# Rename columns for consistency and easier readability

df= df.rename(columns=
    {
    "distancefromhome" : "distance_from_home",
    "environmentsatisfaction" : "environment_satisfaction",
    "jobsatisfaction" : "job_satisfaction",
    "maritalstatus" : "marital_status",
    "monthlyincome" : "monthly_income",
    "numcompaniesworked" : "num_companies_worked",
    "worklifebalance" : "work_life_balance",
    "yearsatcompany" : "years_at_company"
    })

In [21]:
# View unique categories in attrition column

df["attrition"].unique()

array(['Yes', 'No'], dtype=object)

In [22]:
# Count employees who stayed vs left the company

df["attrition"].value_counts()

No     1233
Yes     237
Name: attrition, dtype: int64

In [23]:
# View unique department names

df["department"].unique()

array(['Sales', 'Research & Development', 'Human Resources'], dtype=object)

In [24]:
# Count number of employees in each department

df["department"].value_counts()

Research & Development    961
Sales                     446
Human Resources            63
Name: department, dtype: int64

In [25]:
# Compare attrition counts across departments

df.groupby("department")["attrition"].value_counts()

department              attrition
Human Resources         No            51
                        Yes           12
Research & Development  No           828
                        Yes          133
Sales                   No           354
                        Yes           92
Name: attrition, dtype: int64

In [26]:
# Calculate attrition percentage by department

pd.crosstab(df["department"],df["attrition"], normalize= "index").round(2) * 100

attrition                 No   Yes
department
Human Resources         81.0  19.0
Research & Development  86.0  14.0
Sales                   79.0  21.0

In [27]:
# Export cleaned dataset for SQL and Tableau analysis

df.to_csv("cleaned_hr_data.csv", index=False)